server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/huijintian/spring-cloud-config-repo
          search-paths: licensingservice,organizationservice
          username: native-cloud-apps
          password: 0ffended
